name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: adhi18s/clg-notes-project:latest
        cache-from: type=registry,ref=adhi18s/clg-notes-project:latest
        cache-to: type=inline

    - name: Debug - Check DockerHub Image
      run: docker pull adhi18s/clg-notes-project:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull adhi18s/clg-notes-project:latest || exit 1
          docker stop $(docker ps -q --filter ancestor=adhi18s/clg-notes-project:latest) || true
          docker rm $(docker ps -a -q --filter ancestor=adhi18s/clg-notes-project:latest) || true
          docker run -d -p 80:80 adhi18s/clg-notes-project:latest || exit 1
